### ISSUE TITLE
@elastic/charts 73 fails in Create React App 5 because React Redux v9 .cjs is emitted as an asset

### ISSUE THREAD

**Issue by arcoirisapp** [elastic/elastic-charts#2881]
@elastic/charts 73 fails in Create React App 5 because React Redux v9 .cjs is emitted as an asset

After upgrading @elastic/charts from 71.7.0 to 73.0.1 in a Create React App 5 application, every chart fails at runtime with:

TypeError: (0, react_redux_1.connect) is not a function

Environment:
- @elastic/charts: 73.0.1
- react / react-dom: 18.2.0
- react-scripts: 5.0.0
- webpack: bundled through Create React App 5
- Yarn: 1.22.19

Charts 73 depends on react-redux 9.2.0. Its CommonJS entry loads
`react-redux.development.cjs`.

CRA 5's webpack fallback does not treat `.cjs` as JavaScript. It emits that
file as `asset/resource`, so the generated bundle effectively exports a URL:

module.exports = __webpack_require__.p
  + "static/media/react-redux.development.<hash>.cjs";

Consequently, Elastic Charts receives a string instead of the React Redux
module and `connect` is undefined.

The Charts 73 release correctly documents the React Redux v9 / React 18
requirement, but does not mention this CRA 5 packaging incompatibility.

Is CRA 5 expected to be supported with Charts 73? If so, could Charts expose
an ESM-consumable build path that avoids this CommonJS `.cjs` resolution, or
should this be documented as requiring a consumer webpack override?

As a workaround, we plan to stay on @elastic/charts 72.0.1, which still uses
react-redux ^8.1.3 and works with CRA 5.

thanks.
